### ISSUE TITLE
Mime type detection result may be incorrect

### ISSUE THREAD

**Issue by peter279k** [katzien/PhpMimeType#3]
As title, it seems that using the `pathinfo` to fetch and detect extension name from oncoming files may be incorrect.

Sometimes attacker will change the file name and its extension name to fake the back-end type detector.

To enhance the Mime type detection, I think it should  check the oncoming file contents.

For example, the [selective-php/image-type](https://github.com/selective-php/image-type) package can check the image contents to identify the current image contents.

**Comment by katzien** [comment]
@peter279k wanna make a PR for this? :)

**Comment by peter279k** [comment]
Hi @katzien, thanks for your reply and concern.

I'm happy to create related PR for this issue, but I have some questions about this:

- What content types we want to detect? Images, videos, audios or others?
We've to know that what types should be considered/detected.
- I think there're some existing PHP projects about types detection on GitHub, and we can consider integrating them on this project.

What do you think about this? Thanks.

**Comment by jjsty1e** [comment]
Using file extension to check MIME type is not a good solution, maybe you can use 

```
$finfo = new \finfo('FILEINFO_MIME_TYPE');
$mime = $finfo->buffer(file_get_contents($file));
```

or if the file is an image:

```
$img = getimagesize($file);
$mime = !empty($img['mime']) ? $img['mime'] : null;
```

maybe there is better one, and I haven't test the result both.

**Comment by peter279k** [comment]
Hi @Jaggle, thanks for your suggestion.

It seems that this approach is good, but I'm not sure that repository owner @katzien can approve this or having better approach to resolve this issue.

And the PHP has the native [mime_content_type](https://www.php.net/manual/en/function.mime-content-type.php) function to resolve this issue, too.

**Comment by jjsty1e** [comment]
@peter279k Maybe this is the better one, thanks.

**Comment by katzien** [comment]
In all honesty, I've written this library a good few years ago now and I don't use it for anything anymore, so just go with whatever is the latest way in the industry :) `mime_content_type` is probably the way to go 👍
